repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.1.0
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-autopep8.git
  rev: v1.4.3
  hooks:
  - id: autopep8
- repo: https://github.com/pre-commit/mirrors-eslint.git
  rev: v5.13.0
  hooks:
  - &eslint
    id: eslint
    types: [javascript]
    additional_dependencies:
    - eslint@5.13.0
    - typescript@3.2.4
    - "@typescript-eslint/eslint-plugin@1.2.0"
    - "@typescript-eslint/parser@1.2.0"
  - <<: *eslint
    alias: eslint:ts
    name: eslint:ts
    types: [ts]
